### PR TITLE
ES6

### PR DESCRIPTION
**Pull request by kum-deepak**
It will be branch where all ES6 related work will be carried out. Check #1520 for details and progress.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Looks like you need to check in package-lock.json in order for Travis to run.

**Comment by kum-deepak** [comment]
Pushed.

**Comment by gordonwoodhull** [comment]
Looks like Chrome is hanging, but I guess Travis isn't really a priority if the tests are running locally.

**Comment by kum-deepak** [comment]
@gordonwoodhull, all the basic setup seem reasonable. It will be good time to create a new branch based on this PR and close this one. This will allow us to target next set of PRs to that branch.

**Comment by gordonwoodhull** [comment]
Good idea, I created a new branch `es6` and merged this there.

Please rebase, since I also bumped the version to `4.0.0-alpha.0` and added an example I had sitting around.

**Comment by kum-deepak** [comment]
Thanks!

**Comment by gordonwoodhull** [comment]
Thank you!

**Pull request closed without merging**
