### PR TITLE
ESLint `no-var`, `prefer-const`, and `no-shadow`

### PR DESCRIPTION
**Pull request by kum-deepak**
Configured ESLint to issue error for `no-var`, `prefer-const`, and `no-shadow`.

Also, some dead code removal.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
The meaningless underscores are annoying, but I think it's a good linting rule for this project since there are so many contributors. And there have been a few bugs due to shadowed variables.

I like the `data` for `d`!

**Comment by kum-deepak** [comment]
I also figured out that by choosing proper rules, eslint --fix can do a quite a lot of work. As you were merging I had pushed 3 commits which were supposed to be squashed :smile: 

Please check the last 3 commits related to => functions.

**Comment by kum-deepak** [comment]
Sorry about this, I should write explicitly when a PR is ready to merge.

**Comment by gordonwoodhull** [comment]
Whoops! Sorry, I wasn't paying attention. Want to use the "request review" feature for this?

I think it will be okay to "change history" on the es6 branch - want me to squash those, or revert the whole PR?

**Comment by kum-deepak** [comment]
Just review and squash those.

In future, let us use the "request review".

**Comment by gordonwoodhull** [comment]
Looks good! I love how compact the code is with arrow functions.

Branch es6 is squashed.

**Pull request merged**
