### PR TITLE
Box Plot: Fix keyAccessor, extent filtering, x domain change

### PR DESCRIPTION
**Pull request by mtraynham**
This fixes the data binding between the `g.box` SVG nodes and datum keys.  It should be using the keyAccessor, but it just happens to work here because Crossfilter always has datums with a `key` field.  There are a few other places `dc` does this...

This also fixes filtering with X domains that are not ordinal and use brushing.  The issue can be seen in the examples page, [here](http://dc-js.github.io/dc.js/examples/box-plot-time.html).

### CODE REVIEW

**Comment by mtraynham** [comment]
Seems my own commit suffered from incorrectly accessing the datum's keys...

**Comment by gordonwoodhull** [comment]
Yeah, *a few* places.

```
$ grep \\.key\\b src/* | wc
      33     204    2432
```

:frowning: 

Thanks, this is really helpful!

**Comment by mtraynham** [comment]
33 that's not so bad. Maybe a few are in comments.

**Comment by mtraynham** [comment]
One more change I've added to this.  If the x domain changes, the new width is only applied to the `enter` nodes.  Older nodes retain their old width.  Simple change.

**Comment by gordonwoodhull** [comment]
Thanks @mtraynham! Merged for 2.0 beta 33.

**Pull request closed without merging**
