### PR TITLE
Sunburst

### PR DESCRIPTION
**Pull request by blairn**
I am not good at git, but... I think this is right.
It works, tests, lints. I'll do more clean up in the next few days, along with more charts being pull requested. 

Enjoy!

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Examples are great, but we will need Jasmine tests as well. Please see if you can exercise the functionality with some tests similar to https://github.com/dc-js/dc.js/blob/develop/spec/pie-chart-spec.js

**Comment by blairn** [comment]
I thought I did have tests o.O. I remember writing them, I'll go have a
look now

**Comment by blairn** [comment]
ah, I do have tests, but forgot to commit them :( - me and git have a
difficult arrangement.

How do you want me to add them? commit it and build another pull request
replacing the one I did before? or send it to you so you can commit it in?

**Comment by blairn** [comment]
ah... my tests fail LINT something awful, I'll work on getting them working
^.^ and make a new PR. Good night, and thanks for everything! dc.js
wouldn't be nearly as wonderful without you!

**Comment by gordonwoodhull** [comment]
Yes, adding them to the same branch and pushing them is the right approach. A PR it's always a work in progress. Lmk if you get stuck and I'll help troubleshoot. The tests are often pretty challenging.

**Comment by KatiRG** [comment]
I was able to get the sunburst chart working using the code here https://github.com/blairn/dc.js/tree/sunburst, but the weird this is that it turns all my rowChart bars dark grey. Anyone else find this?

**Comment by KatiRG** [comment]
for now we have just hard-coded it in the css:

`.dc-chart g.row rect {
    fill: #1f77b4;
}`

**Comment by gordonwoodhull** [comment]
@csymill26 asked in #1069 and #781:
> The sunburst is an awesome graph. Is there a way to make it zoomable? I have not been able to make it do so. Also, `.innerRadius` does not seem to work for me either. No matter the value I give it, the inner ring is the same size. I saw someone else mentioned having this problem. Is there a fix? Another thing, is it possible to add spaces between the levels? Thanks!

**Comment by gordonwoodhull** [comment]
@csymill26, would you expect the sunburst also to "filter in" to the zoomed part, or is it just a view thing. Also what would be the interface, something like single click to filter, double click to zoom?

**Comment by csymill26** [comment]
Zooming in would be a visual thing as well as a filter thing.  It doesn't matter to me if it's a single or double click to zoom.

**Comment by csymill26** [comment]
Couple questions:  Is the inner radius value working yet?  Will you add zooming?  If it/they are not working yet, when will these become available?  Thank you!

**Comment by gordonwoodhull** [comment]
Unfortunately I think @blairn is quite busy, since he hasn't gotten back to this PR for a while. I'd be willing to write the tests if someone else wants to implement these features. 

@csymill26, probably your best bet if you need this stuff immediately is to start from Blair's source and make the changes yourself. Then please file another PR with your updates!

**Comment by gordonwoodhull** [comment]
Oops, I missed the tests being added. That's awesome. I guess it is on me to get them running properly.

**Comment by staveris** [comment]
Hi regarding innerRadius, i noticed that in dc.js line 4548 [here](https://github.com/blairn/dc.js/blob/sunburst/dc.js#L4548) inner and outerradius are set as functions of d.y and d.dy. I replaced them with .innerRadius(_innerRadius) and it works. I am not sure if some else is lost though

**Comment by gordonwoodhull** [comment]
Merged via #1388 for 3.0.0

**Pull request closed without merging**
