### PR TITLE
D3 v5 GitHub

### PR DESCRIPTION
**Pull request by kum-deepak**
Cherry-picking infra/test/build related commits from `develop` and adding to `dc-v5` branch.

### CODE REVIEW

**Comment by kum-deepak** [comment]
Wow, it failed for no reason. MacOS tests are slowest to complete. Probably we can test only for Safari on macOS.

**Comment by kum-deepak** [comment]
Rerunning the test - success on macOS.

**Comment by gordonwoodhull** [comment]
Is it possible to see old runs? I couldn't find the failure.

Sure, I think it would be okay to test only Safari on macOS. I don't remember seeing too many OS-specific (as opposed to browser-specific) errors.

However, it looks like Windows is often slower than macOS.

**Comment by kum-deepak** [comment]
I think it overwrote that record. I chose to rerun the failed test. In the details, Safari had disconnected twice before it could finish all the tests.

On another note, since Github allows multiple tasks, we can consider setting up one for linting as well.

**Pull request merged**
