### PR TITLE
Inline `pluck` and move it to compat layer

### PR DESCRIPTION
**Pull request by kum-deepak**
We had discussed this when doing ES6 conversion. Finally did it :smile:. Changes span multiple files, however, the pattern is similar. 

In three places 2 argument version was used, it was first fetching the title accessor for the stack and then using it to get the actual title (Line and Bar charts).

The original function has been moved to the compat layer.

### CODE REVIEW

**Comment by kum-deepak** [comment]
I am unclear, so, need your inputs. For the two-argument version, which one you like better:

```typescript
            dot.append('title').text( (d, i) => this.title(d.name)(d.data, i));
```

or

```typescript
            dot.append('title').text( (d, i) => {
                const titleAccessor = this.title(d.name);
                return titleAccessor(d.data, i);
            });
```

**Comment by kum-deepak** [comment]
I realized creating `_extTitleAccessor` in `StackMixin` gives best of both options.

**Comment by kum-deepak** [comment]
I am ready to merge this.

**Comment by gordonwoodhull** [comment]
Otherwise this looks like a nice improvement. Just want to be careful.

**Comment by kum-deepak** [comment]
Valid points. Currently, I find it is alright to keep the two-argument version as it was. I have a sense that this code may be impacted by the data provider concept that I am planning to work on. After that, if needed, I will come back to this.

**Pull request merged**
