### PR TITLE
Boxplot enhancements

### PR DESCRIPTION
**Pull request by cwolcott**
This is my first contribution to a github library.  I have demonstrated the boxplot enhancements in Issue [1370](https://github.com/dc-js/dc.js/issues/1370).  This enhancement should also fix [1120](https://github.com/dc-js/dc.js/issues/1120).

I am currently using 2.1.9 in our code baseline, but have submitted this pull request after branching from 2.1.10.  Once I can get some feed back, I will be happy to add additional test to the box-plot-spec and make sure the documentation for the new attributes are correct.

d3.box.js now has a cyclomatic complexity score of 18.  I assume I need to fix this.

Once this is integrated into the 2.1 branch, I will be happy to look at integrating it with 3.x

### CODE REVIEW

**Comment by cwolcott** [comment]
I think that is it.  Please look at the 2 new examples:

- boxplot enhancements

- boxplot render data

When running **grunt lint --force** I still have a cyclomatic complexity of 18 on d3.box.js.  I assume you would like to me to see if I can refactor the code.

**Comment by gordonwoodhull** [comment]
I'm surprised that a couple of new if statements could push the cyclomatic complexity that high. 

I am somewhat dubious of this metric: that code doesn't look all that hard to read.

I'd be okay with just disabling that warning for the file or function, as long as the lint is otherwise okay. You can see an example where we disable a jshint error at the top of`src/core.js`

**Comment by cwolcott** [comment]
Here are my responses:

- the "magic number" in yAxisMin & yAxisMax functions (Images show numbers of 0, 8, 16, 96)
Forces a minimum pixel padding on the Y Axis.  I am changing the magic number to 8.
So if the magic number is 8, minimum data value is 1 and the yAxisPadding is 0 then the chart yAxisMin is 0.0095.  Without the magic number the box plots would be drawn as in chart 1.
magicnumber 0magicnumber 08magicnumber 16magicnumber 96
I will investigate how other charts might pad the data display a little bit.

The chart yAxisPadding attribute is a unit padding. So if the magic number is 0, minimum data value is 1 and the yAxisPadding is 11 then the chart yAxisMin is -10.

- The yAxisRangeRatio uses the (max data value - min data value) / chart height.  This is then used to multiple by 8 to determine the padding to use on the yAxis.  Previously the developer defaulted the yAxisPadding to 12 which caused the issue for #1120. This fixes that.

- I will resubmit another pull request and let you know when I think it is ready for review again.

**Comment by gordonwoodhull** [comment]
You can push more commits to the same branch and they will be reflected in this ticket automatically. GitHub is amazing!

Let's open up that magic number as a parameter. What you are doing makes a lot of sense but magic numbers are always a recipe for trouble (as `12` was!)

I bet there is a better way to handle that `TODO` like maybe the data is already bound to something closer. At the very least you can always use `d3.select(x).datum()` rather than `x.__data__` - more idiomatic, safer. Have not had a chance to look for myself.

**Comment by gordonwoodhull** [comment]
Another more sophisticated way to implement padding is have a pixel padding parameter, then use [`scale.invert()`](https://github.com/d3/d3-scale/blob/master/README.md#continuous_invert) (somehow, but I haven't thought it through completely) to determine the amount to add to the domain to allow that many pixels of padding in the range.

I know we have the same problem with the bar chart labels above the bars, but I think people just use the [margins](http://dc-js.github.io/dc.js/docs/html/dc.marginMixin.html) to work around it. Ugly, but better than manipulating the domain to fit something measured in pixels.

Just giving some background here, don't feel obligated to pick it up. Ideally this would be something at the coordinate grid mixin level. We have domain padding but we also need range padding.

**Comment by cwolcott** [comment]
I have changed the parameter for getColor to your suggestion: d3.select(this).datum()

I just played around with invert, but it was always returns the value I passed in.
_chart.y().invert(1) returned 1, 100 returns 100.  So I will keep the current code for now since the chart looks good for any number range and continue to research.  Just to give you an idea of the current code (with the Magic Number set to 8).

minDataValue = 1; maxDataValue = 27; yAxisRangeRatio = 0.1238; padding = 0.9904;
minDataValue = 1; maxDataValue = 100; yAxisRangeRatio = 0.4714; padding = 3.7714;
minDataValue = 1; maxDataValue = 1000; yAxisRangeRatio = 4.7571; padding = 38.0571;

minDataValue = 1001; maxDataValue = 1027; yAxisRangeRatio = 0.1238; padding = 0.9904;

**Comment by cwolcott** [comment]
I am done unless you have more suggestions.

**Comment by gordonwoodhull** [comment]
I just looked at the demos for the first time. Excellent work!

I am changing a few names for clarity:
 * `renderData` -> `renderDataPoints` (not exactly the same functionality as [lineChart.renderDataPoints](http://127.0.0.1:8888/web/docs/html/dc.lineChart.html#renderDataPoints__anchor), but it could be upgraded to allow setting individual SVG attributes, in a backward-compatible way, in the same way that function was)
 * `dataBoxPercentage` -> `dataWidthPortion` (awkward but more descriptive I think)

The datum is passed as the first parameter, so `d3.select(this).datum()` is just `d`!

You are right that `scale.invert()` won't work in `yAxisMin` and `yAxisMax`... because the scale has not yet been initialized; these calculations are used to calculate the domain for the scale. What you are doing should be equivalent: adding some padding in pixel coordinates, specifically a bit more than half of the font height.

I'd really like to see this promoted to `coordinateGridMixin` someday. For now I am renaming `_internalRangePadding` and exposing `yRangePadding` as a getter/setter (no longer "magic"). This is necessary because the user can change the font using CSS ` .dc-chart .box text`. We do not currently try to measure font sizes anywhere, so there are these little knobs everywhere.

It wasn't necessary to define `renderTitle` because it is already a member of `baseMixin`.

**Comment by gordonwoodhull** [comment]
I also restored the necessary changes for D3v4. This will be released in 3.0.4

**Comment by gordonwoodhull** [comment]
Thanks @cwolcott!

**Comment by cwolcott** [comment]
@gordonwoodhull will this also be included in a 2.1.x release?

I have not worked with dc.js 3.0.x line yet, but do you want me to develop a pull request for this or have you already done it?

**Comment by gordonwoodhull** [comment]
I wasn't planning to do a 2.* release for this but I could without too much difficulty. 

I should still have the right commit at home since I made my changes before rebasing onto develop. I'll check tonight.

**Comment by gordonwoodhull** [comment]
Okay, I've published 2.2.0!

(And started a support branch `support/2.x` for future requests of this nature.)

**Comment by cwolcott** [comment]
Thanks @gordonwoodhull.  Just integrated 2.2.0 into all of our examples and our application.  I notified several other folks that 2.2.0 with the enhanced BoxPlots is available.  Hopefully we will upgrade to the 3.x line over the next month.

**Pull request closed without merging**
