### PR TITLE
Transition delay

### PR DESCRIPTION
**Pull request by mbustosorg**
Adding the ability to specify the transition delay in addition to transition duration.  This allows you to create some more interesting transition flows by adjusting when the transitions would start.  

      .transitionDelay(function (d,i) {
	  return Math.floor((Math.random() * 1000) + 1);
       })

This creates a random 0-1 second delay which can give the transition another dimension.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Hey @mbustosorg did this not work or did you close the PR for another reason? 

Looks interesting.

**Comment by mbustosorg** [comment]
Hi Gordon.

I messed up the pr.  I'm going to resubmit it in the next day.

Thanks for the comment.  Keep an eye out!

Mauricio

**Comment by mbustosorg** [comment]
Hi Gordon,

I'm having trouble getting the tests to pass on the pull request.  It's
#1116.  Tests are passing on my machine but the CI run is failing.  Can you
advise?

Thanks,
mauricio

**Comment by mbustosorg** [comment]
Hi Gordon,

I'm having trouble with the tests.  I'm getting the specs to run fine in
the browser but am seeing:

>> Error caught from PhantomJS. More info can be found by opening the Spec
Runner in a browser.

This is showing up in the Travis CI test also.  If I use the --force all
tests pass.

Have you seen this before?

Thanks,
mauricio

**Comment by gordonwoodhull** [comment]
Moving this discussion to the active PR #1116

**Pull request closed without merging**
