### PR TITLE
Fixed test cases for Microsoft Edge

### PR DESCRIPTION
**Pull request by kum-deepak**
Tested with images from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

- Works on Microsoft Edge on Win10. 
- Definitely does not work with IE9 on Win7.

How do I enable cross browser tests for the PRs?

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
That's great! 

How bad is the breakage in IE9? Is it d3 stuff? Stuff that can be polyfilled? Are you able to test IE10?

**Comment by gordonwoodhull** [comment]
Thanks for enabling the cross browser tests too!

**Comment by kum-deepak** [comment]
In IE9, not really sure. But on that browser even the current version does not seem to work.

**Comment by kum-deepak** [comment]
I will try with IE10 next.

**Comment by gordonwoodhull** [comment]
Okay, sure, don't worry about it too much. IE11 is plenty.

 I'll revisit IE9 some other time. It mainly matters in corporations with outdated technology.

**Comment by kum-deepak** [comment]
The sauce lab tests timed out. Please check the output above to see if I have misconfigured something.

Is there a way to invoke saucelab tasks from my command line?

**Comment by gordonwoodhull** [comment]
I don't know the answer to that, sorry. But saucelabs does just randomly time out sometimes. This may be a busy time of day or something.

When this happens I either push a dummy commit or just assume it's okay.

**Comment by kum-deepak** [comment]
Testcases pass on IE 10, Win7. Stocks example on homepage seems to work.

**Comment by gordonwoodhull** [comment]
Did the dummy commit still fail? I got an email about it but can't find the commit on GitHub .

I think it must have been this Travis run, based on the timing: https://travis-ci.org/dc-js/dc.js/builds/357234955

Sorry about that! Perhaps there is a bug that prevents pull requests from working correctly on saucelabs. Or perhaps you were just very unlucky in your timing.

Anyway, I trust that this PR is good and will merge it soon. Please proceed with the other items in separate branches.

I'm still very slow (notice I am opening about one issue/day) but this project is vitally important to me. You have no idea how much I appreciate your work on this.

**Comment by kum-deepak** [comment]
Thanks for your detailed information. It does work on IE10 and Edge as tested on VMs in my machine. The tests failed after the dummy commit, I reverted that commit. I think you should merge it. It will anyway get tested in any of the future full tests.

**Comment by gordonwoodhull** [comment]
Will merge soon, thanks again!

**Comment by gordonwoodhull** [comment]
Realized I can just hit the button on this one, so doing so. We'll see if it breaks all PR testing, might have to revert that commit later.

**Comment by gordonwoodhull** [comment]
Oh wow github won't let me hit the button on my phone. Later then!

**Pull request merged**
