### PR TITLE
Update License year to 2016

### PR DESCRIPTION
**Pull request by pra85**

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
It's definitely valid. I've been considering generating these automatically, actually, which I do on another project.

**Comment by gordonwoodhull** [comment]
Thanks @pra85!

**Comment by pra85** [comment]
Apologies @gordonwoodhull , I closed the PR as I thought it had been abandoned. 

In case you don't want to update license year on a yearly basis, you can switch to an evergreen style `2012-present` (like one used by projects like React - https://github.com/facebook/react/blob/master/LICENSE )

**Comment by gordonwoodhull** [comment]
No, dc.js is not abandoned, although I can never find as much time for it as I'd like.

Huh, I didn't know you could do that, wonder why the evergreen style is not more common. Like it.

**Comment by gordonwoodhull** [comment]
Merging for beta 26. Thanks @pra85!

**Pull request closed without merging**
