### PR TITLE
ES6 compliant docs

### PR DESCRIPTION
**Pull request by kum-deepak**
All src files has been modified one round. Mostly used semi automated conversions with sampled checks. Seems alright for now.

The library is no longer necessarily namespaced under `dc`, this will need updating in main entry point.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Hi @kum-deepak, I'm back from vacation today.

This cleans up the documentation nicely. But it's a little frustrating that it breaks all links into the documentation. When I answer questions on SO I often link to the particular class and method under discussion, and it would be disappointing if all those links died.

Any thoughts about a decent way to redirect each of the files while preserving the fragment id `#`, e.g. `dc.barChart.html#gap` to `BarChart.html#gap`?

**Comment by kum-deepak** [comment]
I was thinking to leave the current documentation on its location and host documentation of this version under a new URL.

I do not expect everyone to shift to this version immediately. So, keeping both versions may be useful.

**Comment by gordonwoodhull** [comment]
I'd rather not keep old documentation alive and I don't think it will be too confusing for people to look at the new documentation, since the external API isn't changing much.

But I like the idea of generating the new docs to a new location since this makes a huge impact on the documentation filenames.

If you know the new location, please update this PR accordingly. Then I can generate the redirect pages sometime before the release.

**Comment by gordonwoodhull** [comment]
Or if you prefer, I can merge this and open an issue to change the path before release.

Thanks for all your hard work, @kum-deepak!

**Comment by kum-deepak** [comment]
I want to update the entry point of the documents. I will let you when it is ready to merge.

**Comment by kum-deepak** [comment]
This is now ready to be merged. The folder restructure will be taken as a different PR.

**Comment by gordonwoodhull** [comment]
Thanks @kum-deepak. I filed issues for each of us for the missing bits.

**Pull request merged**
