### PR TITLE
Paired Row Chart and Row Chart useRightYAxis

### PR DESCRIPTION
**Pull request by ruhley**

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Coooool. One could implement #510 bidirectional row chart with this.

**Comment by ruhley** [comment]
I am working on a Paired Row Chart like [https://reference.wolfram.com/language/ref/PairedBarChart.html](https://reference.wolfram.com/language/ref/PairedBarChart.html) if that is what you mean by a bidirectional row chart.

This is a precursor to getting the paired row chart (or whatever you want to call it) to work.

**Comment by ruhley** [comment]
I have just noticed that the animation when rendering is still going from right to left. If you hold off for a bit I can get that to work from left to right as well.

**Comment by gordonwoodhull** [comment]
Yeah exactly, see the link to #510 above. Usually used for gender vs age distribution.

Thanks for the row example, that's been missing.

I'm going to have to wait for tests (nudge, or write them myself), so no rush...

**Comment by ruhley** [comment]
I have fixed up the animation for row charts that are right aligned and also added tests. How does it all look?

**Comment by ruhley** [comment]
@gordonwoodhull I have implemented the paired row chart, included examples and tests. I feel it is a little hacky by having two sub row charts, but all in all it works great for me. I had to change the row chart slightly to get it to work.

Take a look at the [example](https://github.com/dc-js/dc.js/pull/943/files#diff-fcc50b70a2594460c1d2f27a1091a824) for how it works.

**Comment by gordonwoodhull** [comment]
Ooops, usually the best practice is to create a feature branch when contributing a PR. This has a ton of other changes in it now. I think I can sort through and find the changes that are relevant to this feature. 

Sorry for the extreme lag in merging this! It's hard to find the time for a careful review.

**Comment by ruhley** [comment]
Yea, I realised that I probably should have done that a bit late, which is why I updated the [changelog](https://github.com/ruhley/dc.js/blob/develop/Changelog.md#ruhley-changes), so that anyone could find the commits for each feature easier.

**Comment by gordonwoodhull** [comment]
Yes, that is very helpful! Probably what needs to happen next is for someone (could be me or anyone with decent git fu) to create a PR with just those changes. I have to review changes mostly independently.

**Comment by gordonwoodhull** [comment]
Replaced by #1068, with just the relevant commits.

**Pull request closed without merging**
