### PR TITLE
Remove d3v5 compat

### PR DESCRIPTION
**Pull request by kum-deepak**
Ref #1846 

I am targeting d3@v7. I have checked the changelog between v6 and v7, it does not seem that dc is affected by any breaking changes. So, most likely dc will work with d3@v6 as well.

In the first commit, I have removed the nest helper and inlined relevant parts of the code.

### CODE REVIEW

**Review by gordonwoodhull — APPROVED** [review]
I haven't tested, but this looks great.

Interesting that we only use d3.mouse for a debug thing. Looks like d3.pointers is supposed to replace this. https://github.com/d3/d3-selection/pull/253

Only adaptHandler left! This one is a big task but it will make the code much more readable to use d3@6+ handler signature and no wrapper.

**Comment by kum-deepak** [comment]
Next, I will work on d3.mouse. I realized it has been added to compact for dc@v4 (https://github.com/dc-js/dc.js/pull/1808 and https://github.com/dc-js/dc.js/issues/1807).

**Comment by kum-deepak** [comment]
Completed for now. @gordonwoodhull please check when you have time.

**Review by gordonwoodhull — CHANGES_REQUESTED** [review]
Wow, it's so much easier to read the event handlers with the idiomatic D3 handler signature and no `adaptHandler`.

One quibble: I'd prefer to inline `{}` rather than declaring `dummyEvent` every time we need a dummy event. It's not like we have to document what the parameter is for, since anyone working on dc.js should understand D3 idioms.

**Review by gordonwoodhull — APPROVED** [review]

**Comment by gordonwoodhull** [comment]
Thanks @kum-deepak!

**Comment by kum-deepak** [comment]
Next, I will sync examples from the current develop branch and upgrade those to the latest syntax. After that, I will complete the migration guide.

**Pull request merged**
