### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ali-master**

### CODE REVIEW

**Comment by ali-master** [comment]
Every programmer knows how they can run every application by seeing the package.json and we don't need to write a shorthand description.

Thank you.

**Comment by gordonwoodhull** [comment]
Not every programmer is originally a JS programmer, but sure, point taken.

**Comment by gordonwoodhull** [comment]
Thanks @ali-master!

**Comment by ali-master** [comment]
Thank you too.

**Pull request merged**
