### PR TITLE
GitHub actions - Ubuntu, Windows, and macOS 

### PR DESCRIPTION
**Pull request by kum-deepak**
The initial version, currently it runs our current test workflow on the latest Ubuntu, Windows, and macOS.

These should be possible to be extended to include OS/browser combinations that we intend to test.

### CODE REVIEW

**Comment by kum-deepak** [comment]
Current config:

- Chrome, Firefox on Ubuntu
- Edge, Chrome, Firefox on Windows
- Safari, Chrome, Firefox on MacOS

Latest OS, Node 12

**Comment by kum-deepak** [comment]
I have removed Saucelabs related settings.

**Comment by kum-deepak** [comment]
Safari Headless is not supported with the NPM version of the plugin, so used from https://github.com/karma-runner/karma-safari-launcher/pull/22

**Comment by gordonwoodhull** [comment]
Wow, this is great!

It's funny that it runs all the tests twice, once for push and once for pull_request, but I guess that is normal.

**Comment by gordonwoodhull** [comment]
This is much faster too!

What a relief to be done with unreliable saucelabs. It was great the first few years but it really deteriorated recently.

**Comment by kum-deepak** [comment]
We can actually drop one of Ubuntu or Travis as both are testing the same stuff.

**Comment by gordonwoodhull** [comment]
Let's drop Travis in a month or two, when we're sure everything is working properly.

It's nice to have the redundancy (especially since it runs in parallel).

**Pull request merged**
