### PR TITLE
Fixes Bug 710 - Heatmap titles don't update on filtering

### PR DESCRIPTION
**Pull request by mtraynham**
Fixes Bug #710

### CODE REVIEW

**Comment by mtraynham** [comment]
It's a shame that you can't change the branch to commit the pull request to... target for `master`.

**Comment by gordonwoodhull** [comment]
I think you have to change it when you're doing the comparison, before you submit the PR

**Comment by mtraynham** [comment]
>Should check your PR, before you wreck your PR.

I'll catch myself next time, XD

**Comment by gordonwoodhull** [comment]
Fixed by #798 / 6269b7e23da514bf1ec08a03c1a7207baa127251

**Pull request closed without merging**
