### PR TITLE
slider input to reassign pieChart

### PR DESCRIPTION
**Pull request by wdingx**
Using slider input threshold to trigger data redistribution in pie chart:
this is useful for comparing data distributions based on various thresholds in plenty of biological studies ( e.g.: core/non-core gene proportion, etc.)

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Great, thanks @wdingx! This will help a lot of people.

**Comment by gordonwoodhull** [comment]
Merged for 2.0 beta 32. Thanks @wdingx!

**Comment by wdingx** [comment]
Thank you!

**Comment by gordonwoodhull** [comment]
Example renamed and launched in 2.0 beta 32. Thanks @wdingx!

http://dc-js.github.io/dc.js/examples/adjustable-threshold.html

**Comment by gordonwoodhull** [comment]
Merged in 2.0 beta 32

**Pull request closed without merging**
