### PR TITLE
Linking an actual boxplot demo

### PR DESCRIPTION
**Pull request by ubershmekel**

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Thanks @ubershmekel, looks like an errant copy-paste. The docs are generated from the source and the correct place to fix this is in src/box-plot.js; will do!

**Comment by ubershmekel** [comment]
Cool. Thanks for the pointer. I updated the source. I did not take the time to regenerate the docs and test though. Feel free to close the PR if you prefer to do it yourself.

**Comment by gordonwoodhull** [comment]
Thanks, I'll pull this in my next sweep!

**Comment by gordonwoodhull** [comment]
Merged in 2.0 beta 26. Thanks @ubershmekel!

**Pull request closed without merging**
