### PR TITLE
Issue #989 - filter handler is inefficient

### PR DESCRIPTION
**Pull request by esjewett**
Addresses issue #989 by removing the unnecessary and inefficient initial filter(null) and introduces logic for using filterExact in situations where it will work.

### CODE REVIEW

**Comment by esjewett** [comment]
I suspect I screwed up this pull request. Anything I can do to help it be merged? Back out and redo without the generated files?

**Comment by gordonwoodhull** [comment]
Don't worry about it, I can handle that as long as the changes to the non-generated files are all intentional.

I just was in a rush before vacation and didn't have time to review and see whether more tests are necessary, etc. I'm back next week and hope to merge then.

My turnaround tends to be frustratingly slow because I try to seriously review everything. There was a time when stuff was getting merged in too fast and it led to a lot of bugs, some still not fixed. :-(

**Comment by esjewett** [comment]
Sorry, didn't realize you were on vacation! Enjoy :-) And +1 for reviewing thoroughly. I'm still not completely clear on all the different filter structures that various dc.js components use, so it would be good if you can take a second look and make sure this won't break anything that's not in the test suite.

**Comment by gordonwoodhull** [comment]
Wow, this "feels" way, way faster on the main demo page! (Admittedly, I haven't benchmarked.)

Next I'll see if I can correctly detect dc.filters.RangedFilter

**Pull request merged**
