### PR TITLE
Add filtering information to the data table

### PR DESCRIPTION
**Pull request by npmiller**
Add the information if a line of the table is filtered or not. This info is stored in a CSS class .selected or .deselected. This allows us to display filtered data on the table as well.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
I think this will be relevant with the fix for #681 and a constellation of other problems which is in [the sync-filter branch](https://github.com/dc-js/dc.js/tree/sync-filter). Linking this to those to merge at the same time, and add a test for this group-as-dimension trick that makes this one work.

**Comment by vmantese** [comment]
http://loganalysis.github.io/analytics-js/ is down. 
npmiller do you mind reposting that?

**Comment by npmiller** [comment]
@vmantese ah, sorry, the url changed, use this one:
https://loganalysis.github.io/analytics.js/

**Comment by vmantese** [comment]
Beautiful.

**Comment by vmantese** [comment]
Can we close this?

**Comment by gordonwoodhull** [comment]
Sure

**Pull request closed without merging**
