### PR TITLE
Propagate filters on composite chart to children fixes #677 and #706

### LINKED ISSUE #677: Composite ordinal chart doesn't redraw filtered then reseted bars properly
``` javascript
chart.options({
                //display
                height: 200,
                width: $('#core_range_man_cat').width(),
                margins: {
                    top: 10,
                    right: 50,
                    bottom: 30,
                    left: 40
                },
                renderHorizontalGridLines: true,
                //x-axis
                xAxisLabel: 'Category',
                x: d3.scale.ordinal(),
                xUnits: dc.units.ordinal,
                elasticX: true,
                //y-axis
                yAxisLabel: 'Compliance %',
                elasticY: true,
                rightYAxisLabel: 'Number of Units',
                brushOn: false,
                //data
                dimension: dimension,
                group: group,
                childOptions: {
                    //display
                    renderDataPoints: {
                        radius: 3
                    },
                    renderArea: false,
                    gap: 1,
                    centerBar: true,
                    //data
                    dimension: dimension,
                    group: group,
                },
                compose: [
                    dc.barChart(chart).options({
                        useRightYAxis: false,
                        colors: d3.scale.ordinal().range(['#3333AA']),
                        valueAccessor: function(d) {
                            return d.value.percentage;
                        }
                    }),
                    dc.lineChart(chart).options({
                        useRightYAxis: true,
                        colors: d3.scale.ordinal().range(['#AA3333']),
                        valueAccessor: function(d) {
                            return d.value.count;
                        }
                    }),
                    dc.lineChart(chart).options({
                        useRightYAxis: true,
                        colors: d3.scale.ordinal().range(['#33AA33']),
                        valueAccessor: function(d) {
                            return d.value.stockedCount;
                        }
                    })
                ]
            }).render()

```

Then if i try

``` javascript
chart.filterAll();
dc.redrawAll();
```

it doesn't redraw the bars properly.

### PR DESCRIPTION
**Pull request by kum-deepak**
Final change is quite small.

All filter related calls eventually call `.filter`, so covering just one case proved to be enough. Got a simpler code by listening to 'filtered' event and replacing filters on children. Overriding was getting messy because coordinate mixin already overrides `filter`.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Seems too simple somehow! 😄 

If this is correct, then `compositeChart.applyBrushSelection` can be eliminated too.

`.on('filtered', ...` should definitely be namespaced because users will listen to it too.

I'll try to devise more tests / examples.

**Comment by kum-deepak** [comment]
Thanks @gordonwoodhull, I had not realized that `compositeChart.applyBrushSelection` has actually become redundant 😃 

Also, had not realized behavior of d3.dispatch with same event names - changed in composite chart, also changed another similar usage in coordinateGridMixin.

I think additional test can be added to one of the existing test groups for setting/removing filter(s) and checking in children. Would you like to take a shot?

**Comment by kum-deepak** [comment]
Added few additional test cases. I think these should cover the updated functionality.

**Comment by kum-deepak** [comment]
I noticed that #1366 also fixes the 'filtered' listener in `coordinateGridMixin`. I think the code in this PR is more consistent with rest of the dc. However it may be worth picking up the test case from #1366.

**Comment by gordonwoodhull** [comment]
Ah, thanks for pointing that out! I'll merge that along with this.

**Comment by gordonwoodhull** [comment]
Thanks @kum-deepak! Merged for 3.0.4

Amazing how simple this turned out to be, after all the other fixes anyway.

I went with namespacing the event with `dcjs-range-chart` and `dcjs-composite-chart`. Rationale is that we still want the user to be able to guess the namespace and remove/replace the listener if they need to. 

The unique ids we use for charts in a page, but there is no risk of the charts interfering with each other here.

I didn't manage to write any more composite chart examples today. Hope to return to that another day!

**Pull request closed without merging**
