### PR TITLE
Added dc.sunburstChart (fixes #781)

### LINKED ISSUE #781: sunburst or nested donut chart
It would be nice to have a sunburst or a nested donut chart directly from dc.js.
I call sunburst or nested donut chart a chart like 
1-sunburst
Is it possible, already done by someone, I would be very interested to know.

### PR DESCRIPTION
**Pull request by tehsenaus**
This is an update of @blairn's original PR at: https://github.com/dc-js/dc.js/pull/907

I've merged with ```develop```, made a few fixes and performance improvements, fixed the unit tests, and code style.

Documentation is missing though, hopefully someone can give me guidance on that.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
@tehsenaus, this is fantastic! Thanks so much for doing this. 

I hope to review soon. In the meantime, documentation is just a matter of adding comments in jsdoc format. It's a bit verbose but it's very powerful, and you could follow the other charts as an example.

We mainly do not use the markdown documentation because it has become too long to browse in one file. Instead, the html docs are the new standard. You can test them by running `grunt server` and then going to 

http://127.0.0.1:8888/web/docs/html/

Any questions, please ask!

**Comment by tehsenaus** [comment]
Hi, I've managed to get around to adding those JSDocs now, you can take a look here:

http://127.0.0.1:8888/web/docs/html/dc.sunburstChart.html

Thanks!

**Comment by gordonwoodhull** [comment]
Awesome. Thanks @tehsenaus!

**Comment by tehsenaus** [comment]
Just following up on this - is it good to merge?

**Comment by gordonwoodhull** [comment]
Sorry for my slow response. Clearly I'm backlogged on dc.js stuff.

Specs, tests, examples... looks like you've provided everything! I just need to find the time to review and merge. 

Hmm, it looks like the index generation for examples is broken in your environment and it inserted `C:\Workspace` hrefs, but that's not a problem since I generate those anyway.

**Comment by kum-deepak** [comment]
@tehsenaus Thanks for your excellent work. I am currently working on upgrading dc to use D3v4 and assisting on preparing next major release of dc (version 3). You can track the progress in 3.0 branch. @gordonwoodhull has planned this PR to be part of this release. I will be working on upgrading this PR for D3v4 and readying for inclusion in dc.

Will really appreciate if you are around and are able to help :)

**Comment by gordonwoodhull** [comment]
Merged via #1388 for 3.0.0

**Pull request closed without merging**
