### PR TITLE
grouped bars, bar value labels, auto-width legend items

### PR DESCRIPTION
**Pull request by wssbck**
This pull request contains all changes made by me to DC.js. It contains quite unclean solutions to the following issues:
- displaying bar and row charts with multiple groups
- displaying values next to rows or on top of bars in row and bar charts
- allowing legend items to preserve spacing when laid out horizontally instead of them using the same horizontal space regardless of the length of their titles

### CODE REVIEW

**Comment by arunksalian** [comment]
Is grouped bar chart support implemented ?

**Comment by gordonwoodhull** [comment]
@arunksalian, this PR implements a lot of things. You may be able to pull just that functionality from it, or use @wssbck's fork of dc.js directly. I was not able to pull this into dc.js mainline in its current state.

**Comment by gordonwoodhull** [comment]
There is another version of this code here:

https://github.com/dc-js/dc.js/issues/558#issuecomment-52504655

**Comment by wssbck** [comment]
@arunksalian, as @gordonwoodhull said, this PR was not supposed to be actually merged, I have opened it only to gather all my modifications in one place so that the team behind DC.js can look at them and perhaps take something they find usable. Hopefully you can look into the code and made some use of it.

**Comment by wssbck** [comment]
@gordonwoodhull I guess this PR can be closed now :-)

**Comment by gordonwoodhull** [comment]
Yeah I think other people took up the ball on all these features. Some are already in 2.0 and the other PRs will be merged for 2.1, time willing.

Thanks for inspiring us onward, @wssbck!

**Comment by wssbck** [comment]
Gerne! :-)

**Pull request closed without merging**
