### PR TITLE
Sunburst dc v3

### PR DESCRIPTION
**Pull request by kum-deepak**
This is an straight upgrade of #1337 with as little changes that I could.

Will look into qualitative aspects soon.

### CODE REVIEW

**Comment by kum-deepak** [comment]
Done with current round of changes.

- Low priority - Can https://github.com/d3/d3-hierarchy/blob/master/README.md#stratify replace  `dc.utils.toHierarchy`?

**Comment by kum-deepak** [comment]
Rebase to `dc.js/develop` caused issues, will investigate before pushing the changes.

**Comment by kum-deepak** [comment]
Well, we have our first case of a feature that work on D3v4 but did not work in D3v5.

Rebased to `dc.js/develop` and then downgraded D3 to v4, works for now. Need to dig deeper. 😄

**Comment by gordonwoodhull** [comment]
Wow very interesting. Details please, when you have time to figure it out!

**Comment by kum-deepak** [comment]
It turned out to be quite simple, the example was using one of scheme category 20 colors. Which was causing all colors to be undefined and the chart to draw everything in white.

I will push a commit soon. 

On April 22, 2018 5:53:55 PM UTC, Gordon Woodhull <notifications@github.com> wrote:
>Wow very interesting. Details please, when you have time to figure it
>out!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dc-js/dc.js/pull/1388#issuecomment-383399697

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kum-deepak** [comment]
The failing test case is probably related to a weak test case in color-spec, will fix that as a separate PR.

**Comment by gordonwoodhull** [comment]
Thanks @blairn, @tehsenaus, @kum-deepak!

This is merged for 3.0.0

**Comment by Frozenlock** [comment]
I'm not sure in which opened or closed Sunburst issues I should ask this...
@gordonwoodhull @kum-deepak 
Would you mind taking a look at my question posted [here](https://groups.google.com/forum/#!topic/dc-js-user-group/KJOAaedtcgM)?

I'm not sure if the problem lies with the value accessor or how I build up my dimensions...

**Comment by gordonwoodhull** [comment]
Hi @Frozenlock! I did see your question on the users group but I didn't know the answer off the top of my head and I got distracted by other things. :) 

It's completely okay to "bump a thread" by replying to yourself, if it's getting ignored. There's always a lot going on.

I'll try to take a look today.

**Pull request closed without merging**
