### PR TITLE
Checkbox filtering dc v3

### PR DESCRIPTION
**Pull request by kum-deepak**
Based on #1348 - updated for D3v4.

### CODE REVIEW

**Comment by kum-deepak** [comment]
Facing a peculiar issue - few test cases fail in phantomjs, but succeed when I run in browser (firefox, safari, chrome) on a Mac. Issue appeared only in current commit, works well with D3v3 (original PR).

**Comment by gordonwoodhull** [comment]
Ugh, that is upsetting. Perhaps phantomjs is falling behind on compatibility with the browsers. I believe it has been abandoned and people have moved on to other headless browsers for testing.

 Perhaps it is time for us to do the same? How do you feel about trying some infrastructure upgrades?

The particular error is 

```
   TypeError: Unable to delete property. in file:///home/travis/build/dc-js/dc.js/web/js/d3.js (line 1303)
   file:///home/travis/build/dc-js/dc.js/web/js/d3.js:1303:37
   selection_each@file:///home/travis/build/dc-js/dc.js/web/js/d3.js:1185:41
   selection_property@file:///home/travis/build/dc-js/dc.js/web/js/d3.js:1310:18
   _doRedraw@file:///home/travis/build/dc-js/dc.js/dc.js:11619:26
   redraw@file:///home/travis/build/dc-js/dc.js/dc.js:1849:38
   redrawAll@file:///home/travis/build/dc-js/dc.js/dc.js:369:25
   redrawGroup@file:///home/travis/build/dc-js/dc.js/dc.js:1900:25
   file:///home/travis/build/dc-js/dc.js/dc.js:11725:31
   trigger@file:///home/travis/build/dc-js/dc.js/dc.js:972:16
   onChange@file:///home/travis/build/dc-js/dc.js/dc.js:11724:26
   file:///home/travis/build/dc-js/dc.js/spec/cbox-menu-spec.js:191:27
```

I could be wrong, but I am guessing this means that `d3.selection.property` has changed its implementation somehow for the case where a property should be deleted (when the value is null).

I believe there's  only one line that could trigger this, here:

```js
                .property('checked', function (d) {
                     return d && _chart.filters().indexOf(String(_chart.keyAccessor()(d))) >= 0;
                 });
``` 

https://github.com/dc-js/dc.js/pull/1389/files#diff-7dc7e6020cb53b43b5397330e4dc33d2R76

So you could try adding `|| false` in case d is null.

**Comment by kum-deepak** [comment]
@gordonwoodhull you are a genius 👍 

I am creating a new task for infrastructure upgrades.

**Comment by kum-deepak** [comment]
Complete my work for now. Moving onto next PR.

**Comment by kum-deepak** [comment]
Rebased and changed base to `dc.js/develop`.

**Comment by gordonwoodhull** [comment]
Thanks @ialarmedalien, @kum-deepak!

Merged for 3.0.0

**Pull request closed without merging**
