### PR TITLE
Checkbox/radio button filtering

### PR DESCRIPTION
**Pull request by ialarmedalien**
I'm a fan of checkbox and radio button-styled filters, so I've added `dc.cboxMenu`, which functions similarly to `dc.selectMenu` but uses either radio buttons (for single selection) or checkboxes (multiple selection) instead of the `select` element.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Thanks for the contribution! Sounds like a neat idea.

Looks like you need to add the new file to Gruntfile.js (or commit the gruntfile if you've done this already) so that it will get picked up in dc.js and Travis will run the tests.

**Comment by gordonwoodhull** [comment]
Thanks! The build is passing now. Looking forward to trying this out, but I have to warn you that I am somewhat backlogged and I may not start reviewing/merging until after next week. 

As you can see, there are quite a lot of open PRs, but not too many have working tests (thank you!!), so these will have priority.

**Comment by kum-deepak** [comment]
@ialarmedalien Thanks for your excellent work. I am currently working on upgrading dc to use D3v4 and assisting on preparing next major release of dc (version 3). You can track the progress in 3.0 branch. @gordonwoodhull has planned this PR to be part of this release. I will be working on upgrading this PR for D3v4 and readying for inclusion in dc.

Will really appreciate if you are around and are able to help :)

**Comment by ialarmedalien** [comment]
Apologies, I only just saw this message - I would have been happy to help, but it looks like you've completed the task!

**Comment by gordonwoodhull** [comment]
Merged via #1389

**Pull request closed without merging**
