### PR TITLE
Restructure folder structure

### PR DESCRIPTION
**Pull request by kum-deepak**
See #1598, #1579, #1565

### CODE REVIEW

**Comment by kum-deepak** [comment]
I am planning to make test running independent of `web/`.

**Comment by kum-deepak** [comment]
Please review and see everything makes sense. Completed work from my end.

**Comment by kum-deepak** [comment]
I realized that link for source code link for examples examples will break when this version is released. Please let me know if I should fix those in this PR or in another PR when this one is merged.

**Comment by gordonwoodhull** [comment]
This is a huge change! I like the approach of keeping everything in the same place on the external site, but removing the output directory from the sources.

Unfortunately this seems to have caused some eslint breakage:
1. The lintable files list includes `web/stock.js` which is an artifact which doesn't exist until `grunt copy` is called.
2. eslint is now checking a number of 3rd party files which fail:

```
/home/gordon/src/dc.js/spec/3rd-party/compare-versions.js
/home/gordon/src/dc.js/spec/3rd-party/crossfilter.js
/home/gordon/src/dc.js/spec/3rd-party/d3.js
/home/gordon/src/dc.js/spec/helpers/jasmine-jsreporter.js
```

As an aside, it also seems that the eslint update from last week requires a newer version of node (due to using newer regexp flags). I have node 8.9.1 and I am wary of upgrading. I backed out to eslint 6.5 and am up and running again - will look into this later.

I'm pushing a fix for the documentation links. Please look into the linting issues and update this PR.

**Comment by kum-deepak** [comment]
Fixed list of files for linting.

I have started using `nvm` for my node version management. Different projects like different ones. For dc I have using node v11.

**Comment by kum-deepak** [comment]
Our Travis build also use node v11.

**Comment by gordonwoodhull** [comment]
Thanks for the `nvm` tip! The reason I have been fearful of changing node versions is `node-sass`, which is incompatible with many versions, especially on Linux. `nvm` makes it easy to switch: I tried node v13 and then dropped back to v11 when that didn't work.

It's kind of hard to keep up with all the consequences, but I think this PR cleans up the generation while being 100% backward-compatible and URL-preserving. My only question was about #1598, which I asked over there.

Thanks @kum-deepak!

**Pull request merged**
