### PR TITLE
Sunburst fixes

### PR DESCRIPTION
**Pull request by ialarmedalien**
This fixes [#1467](https://github.com/dc-js/dc.js/issues/1467), the absent transitions in the sunburst chart. Includes an edit to `safeArc` to reorder params and remove the unnecessary `i` argument.

### CODE REVIEW

**Comment by tttp** [comment]
Hi,
Why did you upgrade grunt? is there something incompatible with the existing version?

**Comment by ialarmedalien** [comment]
I ran `npm audit fix` after installing the various node modules as there were a number of security issues flagged; the updated `grunt` is probably a result of that. (Rerunning it reveals a further 27 security vulnerabilities, including six serious ones.)

**Comment by gordonwoodhull** [comment]
This works very well! Thank you, I hope to merge this soon.

I find the history of this branch a little confusing, so I think I will just take the last commit (ccbf7c2), and do the npm updates separately. Seems to work!

Although it is important to stay up-to-date, we generally aren't exposing our users to any security vulnerabilities - these flaws invariably arise on the `devDependencies` side, so we may have insecure testing environments, but that's not a big deal. I don't think anyone is putting our `grunt server` into production. (I hope not!)

**Comment by gordonwoodhull** [comment]
Thanks @ialarmedalien! This looks amazing, and really helps see what just happened when you filter.

Merged for 3.0.7

**Pull request closed without merging**
