### PR TITLE
Update dc.js

### PR DESCRIPTION
**Pull request by pfafman**
Cross filter community fork: crossfilter2 is needed int the require statement

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Thanks @pfafman, I'm pulling commit e380307b54c199d6311d8f2c0d65903a1ebb36c9 into the 2.0 beta 28 release. (There are some other commits on this branch which I don't think are relevant.)

**Comment by pfafman** [comment]
Gordon,  

This is still an issue in the last deployed NPM.  the dc.js file still is requiring crossfilter and not crossfilter2

Tim

**Comment by gordonwoodhull** [comment]
Drat! I hadn't noticed that you made the change to the output file rather than the input; it belongs in src/footer.js. 

I'll do another release this morning.

And check the rest of the PRs I merged! I usually catch that!

**Comment by pfafman** [comment]
Sorry about that.  It was a quick fix so I could get it to work.

**Comment by gordonwoodhull** [comment]
Fixed for real in 2.0 beta 29

**Pull request closed without merging**
