### PR TITLE
Mixins to classes

### PR DESCRIPTION
**Pull request by kum-deepak**
I have converted Stack and Margin mixins to proper classes. Do you reckon any of the other could be converted as well?

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Sorry.... I forgot that the major problem solved by mixins in dc.js is not "mix and match" (which we don't have), but multiple inheritance. 

All the solutions I can find for MI in JavaScript are not prototype-based. 

I am inclined to leave the hierarchy as it is, with the clever "dynamic inheritance" you discovered. The only problem it is causing is slightly more complicated jsDoc. (#1589)

**Comment by kum-deepak** [comment]
Please merge this commit. With these two, 4 of the 'mixins' are classes (Base and Coordinate apart from these two). It does help.

**Comment by gordonwoodhull** [comment]
Okay, I'll do that. Thanks for your patience!

**Comment by gordonwoodhull** [comment]
Rebased and merged.

**Pull request closed without merging**
