### PR TITLE
Scatter plot titles

### PR DESCRIPTION
**Pull request by daniel-gall**
Candidate to address issue 554:

https://github.com/dc-js/dc.js/issues/554

### CODE REVIEW

**Comment by daniel-gall** [comment]
Correction: wrong issue.  This is the issue addressed:

https://github.com/dc-js/dc.js/issues/961

**Comment by gordonwoodhull** [comment]
I'll review this more thoroughly when I return from vacation next week. A few notes at first glance:

 - It doesn't look like `tooltips` is used - `g` is created from it and then unused. I don't think the title element needs a drawing layer.

 - There aren't really stacks or layers for the scatter plot - these are used for stacked charts like the line chart and bar chart. So I think that's another unnecessary complication. Really `renderTitle` is doing all the work here.

 - Please add a couple of tests to [the Jasmine test](https://github.com/dc-js/dc.js/blob/develop/spec/scatter-plot-spec.js) - one for the default behavior, and one for a custom title.

Overall this is a helpful contribution but I think it could be a lot simpler. Thanks!

**Comment by daniel-gall** [comment]
Thanks for the onceover and comments.

Will look at tooltips.

I tried getting rid of the layers, but it didn't work without them.  I'll have to look into why that might be. Plus I was borrowing from lineChart's code.

I didn't add any tests because the lineChart only had one test - on a meta-feature, not core functionality.   if a bool is set, don't render titles.  I didn't know if that was handled by the base mixin or something.

Sorry for being a first time contributor.  At least I read the guidelines? ;)

**Comment by daniel-gall** [comment]
Will make another PR with the updated scatterPlot.js.  No Jasmine tests incoming yet.  I want to get this in then take the time to understand Jasmin so I don't submit something terribad.

**Pull request closed without merging**
