### PR TITLE
Drop bower support.

### PR DESCRIPTION
**Pull request by kum-deepak**
Bower does not seem to be maintained https://bower.io/blog/2017/how-to-migrate-away-from-bower/.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Sigh, I’ve not been keeping it up to date either, see #1458

**Comment by kum-deepak** [comment]
None of the new versions of npm, rollup, webpack, yarn are going to play nice with bower. I do not see why we should still maintain it.

**Comment by kum-deepak** [comment]
If we decide to keep it, we should automate generation of `bower.json`.

**Comment by gordonwoodhull** [comment]
I agree. I’ll update it in v3, and before merging this for v4 I just want to verify there aren’t any further comments or workarounds referring to bower. (Not at a real computer atm :)

**Comment by gordonwoodhull** [comment]
Please add a note to the migration guide!

**Comment by kum-deepak** [comment]
Done!

**Comment by gordonwoodhull** [comment]
We are following [How to drop Bower support](https://bower.io/blog/2017/how-to-drop-bower-support/) perfectly with the version change. 

Will update the versions on develop for another 3.0 release, and the changelog can serve as notice that we're dropping Bower.

Thanks @kum-deepak, rebased and merged.

**Pull request closed without merging**
